question_data = [

    {"category": "Geography", "type": "multiple", "difficulty": "easy", "question": "What is the capital of Denmark?",
     "correct_answer": "Copenhagen", "incorrect_answers": ["Aarhus", "Odense", "Aalborg"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
     "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Animals", "type": "multiple", "difficulty": "hard",
                                       "question": "Which of these animals is NOT a lizard?",
                                       "correct_answer": "Tuatara",
                                       "incorrect_answers": ["Komodo Dragon", "Gila Monster", "Green Iguana"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In &quot;Highschool DxD&quot;, Koneko Toujou is from what race?", "correct_answer": "Nekomata",
     "incorrect_answers": ["Kitsune", "Human", "Kappa"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside "
                 "swimming pools and drinking water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In &quot;Pok&eacute;mon Sun and Moon&quot;, Team Skull took over which town?",
     "correct_answer": "Po Town", "incorrect_answers": ["Heahea City", "Tapu Village", "Iki Town"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "Which 90&#039;s comedy cult classic features cameos appearances from Meat Loaf, Alice Cooper"
                 " and Chris Farley?",
     "correct_answer": "Wayne&#039;s World",
     "incorrect_answers": ["Bill &amp; Ted&#039;s Excellent Adventure", "Dumb and Dumber",
                           "Austin Powers: International Man of Mystery"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
